name: Release Setup EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE for Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --windowed --name artemis artemis/main.py

      - name: Install Inno Setup
        if: runner.os == 'Windows'
        run: |
          choco install innosetup -y

      - name: Build Windows Installer with Inno Setup
        if: runner.os == 'Windows'
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" artemis_installer.iss

      - name: Build AppImage for Linux
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile --name artemis-linux artemis/main.py
          mv dist/artemis-linux dist/artemis-linux.AppImage

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-builds
          path: |
            dist/*
            *.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List artifacts
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/artemis.exe
            artifacts/artemis-linux.AppImage
            artifacts/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}