name: Release Setup EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE for Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --windowed --name artemis artemis/main.py

      - name: Build AppImage for Linux
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile --name artemis-linux artemis/main.py
          mv dist/artemis-linux dist/artemis-linux.AppImage

      - name: Build Windows Installer with Inno Setup
        if: runner.os == 'Windows'
        uses: Minionguide/inno-setup-action@v1
        with:
          path: artemis_installer.iss

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-builds
          path: |
            dist/artemis.exe
            dist/artemis-linux.AppImage
            Output/*.exe

  release-github:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-builds/artemis.exe
            linux-builds/artemis-linux.AppImage
            windows-builds/Output/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}